name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: code_review_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov
    
    - name: Lint with flake8
      working-directory: ./backend
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
    
    - name: Check for tests
      working-directory: ./backend
      run: |
        if [ -d "tests" ]; then
          pytest tests/ -v --cov=app --cov-report=xml
        else
          echo "No tests directory found. Skipping tests."
        fi
    
    - name: Upload coverage (if tests exist)
      if: always()
      uses: codecov/codecov-action@v3
      with:
        files: ./backend/coverage.xml
      continue-on-error: true

  ml-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      working-directory: ./ml-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Check for tests
      working-directory: ./ml-service
      run: |
        if [ -d "tests" ]; then
          pytest tests/ -v
        else
          echo "No tests directory found. Skipping tests."
        fi

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      working-directory: ./dashboard
      run: npm install
    
    - name: Lint
      working-directory: ./dashboard
      continue-on-error: true
      run: npm run lint
    
    - name: Type check
      working-directory: ./dashboard
      continue-on-error: true
      run: npm run type-check
    
    - name: Build
      working-directory: ./dashboard
      run: npm run build
    
    - name: Run tests
      working-directory: ./dashboard
      run: |
        if npm run | grep -q "test"; then
          npm test
        else
          echo "No test script defined. Skipping tests."
        fi
      continue-on-error: true

  build-docker:
    needs: [backend-tests, ml-tests, frontend-tests]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: false
        tags: code-review-assistant:backend-${{ github.sha }}
    
    - name: Build ML service
      uses: docker/build-push-action@v4
      with:
        context: ./ml-service
        push: false
        tags: code-review-assistant:ml-${{ github.sha }}
    
    - name: Build dashboard
      uses: docker/build-push-action@v4
      with:
        context: ./dashboard
        push: false
        tags: code-review-assistant:dashboard-${{ github.sha }}
